### ISSUE TITLE
安装依赖之后插件加载失败，也未出现配置文件怎么解决？

### ISSUE THREAD

**Issue by Valistars** [Nyaacinth/Telekinesis#1]
能否更加详细的描述一下安装及配置步骤，小白腐竹遇到这列问题搞不懂了

**Comment by Nyaacinth** [comment]
劳驾贴一下启动失败的输出信息？

以及这边也推荐您自行排查一下：
Telekinesis 直接依赖的有 nbt, pyyaml 和 MinecraftDataAPI
且 MinecraftDatAPI 自身依赖 hjson
请确认依赖安装齐全

**Comment by Valistars** [comment]
&nbsp;[TaskExecutor/ERROR]: 插件 RegularPlugin[file=Telekinesis.py,path=plugins\Telekinesis.py,state=0] 加载失败




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Nyaacinth/Telekinesis"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月15日(星期四) 下午2:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Nyaacinth/Telekinesis] 安装依赖之后插件加载失败，也未出现配置文件怎么解决？ (#1)





 
劳驾贴一下启动失败的输出信息？

**Comment by Nyaacinth** [comment]
您好，请贴出完整的输出。而不只是一行“加载失败”

**Comment by Valistars** [comment]
&nbsp;[TaskExecutor/ERROR]: 插件 RegularPlugin[file=Telekinesis.py,path=plugins\Telekinesis.py,state=0] 加载失败
Traceback (most recent call last):
&nbsp; File "E:\MCDReforged\mcdreforged\plugin\plugin_manager.py", line 167, in __load_plugin
&nbsp; &nbsp; plugin.load()
&nbsp; File "E:\MCDReforged\mcdreforged\plugin\regular_plugin.py", line 87, in load
&nbsp; &nbsp; self.__load_instance()
&nbsp; File "E:\MCDReforged\mcdreforged\plugin\regular_plugin.py", line 67, in __load_instance
&nbsp; &nbsp; self.module_instance = misc_util.load_source(self.file_path)
&nbsp; File "E:\MCDReforged\mcdreforged\utils\misc_util.py", line 31, in load_source
&nbsp; &nbsp; spec.loader.exec_module(module)
&nbsp; File "<frozen importlib._bootstrap_external&gt;", line 790, in exec_module
&nbsp; File "<frozen importlib._bootstrap&gt;", line 228, in _call_with_frames_removed
&nbsp; File "plugins\Telekinesis.py", line 7, in <module&gt;
&nbsp; &nbsp; import fcntl
ModuleNotFoundError: No module named 'fcntl'

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Nyaacinth/Telekinesis"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月15日(星期四) 下午3:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Nyaacinth/Telekinesis] 安装依赖之后插件加载失败，也未出现配置文件怎么解决？ (#1)





 
您好，请贴出完整的输出。而不只是一行“加载失败”

**Comment by Nyaacinth** [comment]
是由于 Windows 中 Python 不存在 fcntl 模块所致
现尝试以更换到 portalocker 的方式解决

请更新 Telekinesis 到最新并安装依赖 [portalocker](https://pypi.org/project/portalocker) 后查看问题是否解决

**Comment by Valistars** [comment]
解决了，十分感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Nyaacinth/Telekinesis"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月15日(星期四) 下午3:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Nyaacinth/Telekinesis] 安装依赖之后插件加载失败，也未出现配置文件怎么解决？ (#1)





 
是由于 Windows 中 Python 不存在 fcntl 模块所致
 现尝试以更换到 portalocker 的方式来解决
 
请更新 Telekinesis 到最新并安装依赖 portalocker 后查看问题是否解决

**Comment by Nyaacinth** [comment]
已解决

**Comment by Nyaacinth** [comment]
烦请再次更新到 0.3.2-2
引入新的文件锁实现造成了其他 bug ，现已修复

**Comment by Valistars** [comment]
已更新，同时发现在线重载会失败，但是重启之后就能成功加载了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Nyaacinth/Telekinesis"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月15日(星期四) 下午4:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Nyaacinth/Telekinesis] 安装依赖之后插件加载失败，也未出现配置文件怎么解决？ (#1)





 
烦请再次更新到 0.3.2-2
 引入新的文件锁实现造成了其他 bug ，现已修复
